-- create the folder table without the foreign key
CREATE TABLE folders (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    folder_name TEXT NOT NULL
);

-- create the notes table
-- make the foreign keys immediately as the two
-- dependencies exist

CREATE TABLE notes (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
   name TEXT NOT NULL,
    date_published TIMESTAMPTZ DEFAULT now() NOT NULL,
    content TEXT
  folder INTEGER REFERENCES folder(id)
);

--alter folders table
ALTER TABLE folders
  ADD COLUMN note INTEGER REFERENCES note(id);